# Generated by Django 4.0.5 on 2022-06-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_role_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predmeti',
            old_name='bodovi',
            new_name='ects',
        ),
    ]
