# Generated by Django 4.0.5 on 2022-06-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_bodovi_predmeti_ects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predmeti',
            old_name='sem_izvanredni',
            new_name='sem_izv',
        ),
        migrations.RenameField(
            model_name='predmeti',
            old_name='sem_redovni',
            new_name='sem_red',
        ),
    ]
