# Generated by Django 4.0.5 on 2022-06-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_sem_izvanredni_predmeti_sem_izv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='role',
            field=models.CharField(choices=[('profesor', 'profesor'), ('student', 'student')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
