# Generated by Django 4.0.5 on 2022-06-17 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_korisnik_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('izv', 'izvanredni student'), ('red', 'redovni student')], max_length=50),
        ),
        migrations.CreateModel(
            name='Upisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('upisan', 'Upisan'), ('polozen', 'Polozen'), ('izgubljen potpis', 'Izgubljen potpis')], default='upisan', max_length=64)),
                ('predmet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.predmeti')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
